// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.tmps = {};

  root.tmps.people = '<div class="some-class" ><%- model.peoples %></div>';

}).call(this);
